# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
